//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 11/22/2018 2:44:52 AM
namespace LibraryManagement.LibraryClient
{
    
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    public partial class Container : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Titles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Title> Titles
        {
            get
            {
                if ((this._Titles == null))
                {
                    this._Titles = base.CreateQuery<Title>("Titles");
                }
                return this._Titles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Title> _Titles;
        /// <summary>
        /// There are no comments for Levels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Level> Levels
        {
            get
            {
                if ((this._Levels == null))
                {
                    this._Levels = base.CreateQuery<Level>("Levels");
                }
                return this._Levels;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Level> _Levels;
        /// <summary>
        /// There are no comments for TitleCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TitleCategory> TitleCategories
        {
            get
            {
                if ((this._TitleCategories == null))
                {
                    this._TitleCategories = base.CreateQuery<TitleCategory>("TitleCategories");
                }
                return this._TitleCategories;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TitleCategory> _TitleCategories;
        /// <summary>
        /// There are no comments for Books in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Book> Books
        {
            get
            {
                if ((this._Books == null))
                {
                    this._Books = base.CreateQuery<Book>("Books");
                }
                return this._Books;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Book> _Books;
        /// <summary>
        /// There are no comments for BookConditions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BookCondition> BookConditions
        {
            get
            {
                if ((this._BookConditions == null))
                {
                    this._BookConditions = base.CreateQuery<BookCondition>("BookConditions");
                }
                return this._BookConditions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BookCondition> _BookConditions;
        /// <summary>
        /// There are no comments for Fairies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Fairy> Fairies
        {
            get
            {
                if ((this._Fairies == null))
                {
                    this._Fairies = base.CreateQuery<Fairy>("Fairies");
                }
                return this._Fairies;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Fairy> _Fairies;
        /// <summary>
        /// There are no comments for TitleLists in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<TitleList> TitleLists
        {
            get
            {
                if ((this._TitleLists == null))
                {
                    this._TitleLists = base.CreateQuery<TitleList>("TitleLists");
                }
                return this._TitleLists;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<TitleList> _TitleLists;
        /// <summary>
        /// There are no comments for CheckInRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<CheckInRecord> CheckInRecords
        {
            get
            {
                if ((this._CheckInRecords == null))
                {
                    this._CheckInRecords = base.CreateQuery<CheckInRecord>("CheckInRecords");
                }
                return this._CheckInRecords;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<CheckInRecord> _CheckInRecords;
        /// <summary>
        /// There are no comments for Titles in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTitles(Title title)
        {
            base.AddObject("Titles", title);
        }
        /// <summary>
        /// There are no comments for Levels in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLevels(Level level)
        {
            base.AddObject("Levels", level);
        }
        /// <summary>
        /// There are no comments for TitleCategories in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTitleCategories(TitleCategory titleCategory)
        {
            base.AddObject("TitleCategories", titleCategory);
        }
        /// <summary>
        /// There are no comments for Books in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBooks(Book book)
        {
            base.AddObject("Books", book);
        }
        /// <summary>
        /// There are no comments for BookConditions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBookConditions(BookCondition bookCondition)
        {
            base.AddObject("BookConditions", bookCondition);
        }
        /// <summary>
        /// There are no comments for Fairies in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFairies(Fairy fairy)
        {
            base.AddObject("Fairies", fairy);
        }
        /// <summary>
        /// There are no comments for TitleLists in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToTitleLists(TitleList titleList)
        {
            base.AddObject("TitleLists", titleList);
        }
        /// <summary>
        /// There are no comments for CheckInRecords in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToCheckInRecords(CheckInRecord checkInRecord)
        {
            base.AddObject("CheckInRecords", checkInRecord);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"LibraryManagement.ObjectModel\" xmlns=\"http://schemas.microsoft.com/ad" +
                "o/2009/11/edm\"><EntityType Name=\"Title\"><Key><PropertyRef Name=\"Id\" /></Key><Pro" +
                "perty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"" +
                "Edm.String\" Nullable=\"false\" /><Property Name=\"Author\" Type=\"Edm.String\" /><Prop" +
                "erty Name=\"Publisher\" Type=\"Edm.String\" /><Property Name=\"Price\" Type=\"Edm.Decim" +
                "al\" Nullable=\"false\" /><Property Name=\"TitleCategory_Id\" Type=\"Edm.Int32\" Nullab" +
                "le=\"false\" /><Property Name=\"Level_Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Prop" +
                "erty Name=\"IsActive\" Type=\"Edm.Boolean\" Nullable=\"false\" /><NavigationProperty N" +
                "ame=\"TitleCategory\" Relationship=\"LibraryManagement.ObjectModel.LibraryManagemen" +
                "t_ObjectModel_Title_TitleCategory_LibraryManagement_ObjectModel_TitleCategory_Ti" +
                "tleCategoryPartner\" ToRole=\"TitleCategory\" FromRole=\"TitleCategoryPartner\" /><Na" +
                "vigationProperty Name=\"Level\" Relationship=\"LibraryManagement.ObjectModel.Librar" +
                "yManagement_ObjectModel_Title_Level_LibraryManagement_ObjectModel_Level_LevelPar" +
                "tner\" ToRole=\"Level\" FromRole=\"LevelPartner\" /></EntityType><EntityType Name=\"Le" +
                "vel\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nu" +
                "llable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /></En" +
                "tityType><EntityType Name=\"TitleCategory\"><Key><PropertyRef Name=\"Id\" /></Key><P" +
                "roperty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type" +
                "=\"Edm.String\" Nullable=\"false\" /></EntityType><EntityType Name=\"Book\"><Key><Prop" +
                "ertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" " +
                "/><Property Name=\"Barcode\" Type=\"Edm.String\" /><Property Name=\"Title_Id\" Type=\"E" +
                "dm.Int32\" Nullable=\"false\" /><Property Name=\"PurchaseDate\" Type=\"Edm.DateTime\" N" +
                "ullable=\"false\" /><Property Name=\"BookCondition_Id\" Type=\"Edm.Int32\" Nullable=\"f" +
                "alse\" /><Property Name=\"DamLostDate\" Type=\"Edm.DateTime\" /><Property Name=\"Issue" +
                "dStatus\" Type=\"Edm.Boolean\" Nullable=\"false\" /><NavigationProperty Name=\"Title\" " +
                "Relationship=\"LibraryManagement.ObjectModel.LibraryManagement_ObjectModel_Book_T" +
                "itle_LibraryManagement_ObjectModel_Title_TitlePartner\" ToRole=\"Title\" FromRole=\"" +
                "TitlePartner\" /><NavigationProperty Name=\"BookCondition\" Relationship=\"LibraryMa" +
                "nagement.ObjectModel.LibraryManagement_ObjectModel_Book_BookCondition_LibraryMan" +
                "agement_ObjectModel_BookCondition_BookConditionPartner\" ToRole=\"BookCondition\" F" +
                "romRole=\"BookConditionPartner\" /></EntityType><EntityType Name=\"BookCondition\"><" +
                "Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable" +
                "=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /></EntityTy" +
                "pe><EntityType Name=\"Fairy\"><Key><PropertyRef Name=\"Id\" /></Key><Property Name=\"" +
                "Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Name\" Type=\"Edm.String\" " +
                "Nullable=\"false\" /></EntityType><EntityType Name=\"TitleList\"><Key><PropertyRef N" +
                "ame=\"Id\" /></Key><Property Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Proper" +
                "ty Name=\"Name\" Type=\"Edm.String\" /><Property Name=\"Author\" Type=\"Edm.String\" /><" +
                "Property Name=\"Publisher\" Type=\"Edm.String\" /><Property Name=\"Price\" Type=\"Edm.D" +
                "ecimal\" Nullable=\"false\" /><Property Name=\"TitleCategory_Id\" Type=\"Edm.Int32\" Nu" +
                "llable=\"false\" /><Property Name=\"TitleCategory\" Type=\"Edm.String\" /><Property Na" +
                "me=\"Level_Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Level\" Type=\"E" +
                "dm.String\" /><Property Name=\"BookCount\" Type=\"Edm.Int32\" Nullable=\"false\" /></En" +
                "tityType><EntityType Name=\"CheckInRecord\"><Key><PropertyRef Name=\"Id\" /></Key><P" +
                "roperty Name=\"Id\" Type=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Book_Id\" T" +
                "ype=\"Edm.Int32\" Nullable=\"false\" /><Property Name=\"Fairy_Id\" Type=\"Edm.Int32\" Nu" +
                "llable=\"false\" /><Property Name=\"IssueDate\" Type=\"Edm.DateTime\" Nullable=\"false\"" +
                " /><Property Name=\"CheckInDate\" Type=\"Edm.DateTime\" Nullable=\"false\" /><Navigati" +
                "onProperty Name=\"Book\" Relationship=\"LibraryManagement.ObjectModel.LibraryManage" +
                "ment_ObjectModel_CheckInRecord_Book_LibraryManagement_ObjectModel_Book_BookPartn" +
                "er\" ToRole=\"Book\" FromRole=\"BookPartner\" /><NavigationProperty Name=\"Fairy\" Rela" +
                "tionship=\"LibraryManagement.ObjectModel.LibraryManagement_ObjectModel_CheckInRec" +
                "ord_Fairy_LibraryManagement_ObjectModel_Fairy_FairyPartner\" ToRole=\"Fairy\" FromR" +
                "ole=\"FairyPartner\" /></EntityType><Association Name=\"LibraryManagement_ObjectMod" +
                "el_Title_TitleCategory_LibraryManagement_ObjectModel_TitleCategory_TitleCategory" +
                "Partner\"><End Type=\"LibraryManagement.ObjectModel.TitleCategory\" Role=\"TitleCate" +
                "gory\" Multiplicity=\"0..1\" /><End Type=\"LibraryManagement.ObjectModel.Title\" Role" +
                "=\"TitleCategoryPartner\" Multiplicity=\"0..1\" /></Association><Association Name=\"L" +
                "ibraryManagement_ObjectModel_Title_Level_LibraryManagement_ObjectModel_Level_Lev" +
                "elPartner\"><End Type=\"LibraryManagement.ObjectModel.Level\" Role=\"Level\" Multipli" +
                "city=\"0..1\" /><End Type=\"LibraryManagement.ObjectModel.Title\" Role=\"LevelPartner" +
                "\" Multiplicity=\"0..1\" /></Association><Association Name=\"LibraryManagement_Objec" +
                "tModel_Book_Title_LibraryManagement_ObjectModel_Title_TitlePartner\"><End Type=\"L" +
                "ibraryManagement.ObjectModel.Title\" Role=\"Title\" Multiplicity=\"0..1\" /><End Type" +
                "=\"LibraryManagement.ObjectModel.Book\" Role=\"TitlePartner\" Multiplicity=\"0..1\" />" +
                "</Association><Association Name=\"LibraryManagement_ObjectModel_Book_BookConditio" +
                "n_LibraryManagement_ObjectModel_BookCondition_BookConditionPartner\"><End Type=\"L" +
                "ibraryManagement.ObjectModel.BookCondition\" Role=\"BookCondition\" Multiplicity=\"0" +
                "..1\" /><End Type=\"LibraryManagement.ObjectModel.Book\" Role=\"BookConditionPartner" +
                "\" Multiplicity=\"0..1\" /></Association><Association Name=\"LibraryManagement_Objec" +
                "tModel_CheckInRecord_Book_LibraryManagement_ObjectModel_Book_BookPartner\"><End T" +
                "ype=\"LibraryManagement.ObjectModel.Book\" Role=\"Book\" Multiplicity=\"0..1\" /><End " +
                "Type=\"LibraryManagement.ObjectModel.CheckInRecord\" Role=\"BookPartner\" Multiplici" +
                "ty=\"0..1\" /></Association><Association Name=\"LibraryManagement_ObjectModel_Check" +
                "InRecord_Fairy_LibraryManagement_ObjectModel_Fairy_FairyPartner\"><End Type=\"Libr" +
                "aryManagement.ObjectModel.Fairy\" Role=\"Fairy\" Multiplicity=\"0..1\" /><End Type=\"L" +
                "ibraryManagement.ObjectModel.CheckInRecord\" Role=\"FairyPartner\" Multiplicity=\"0." +
                ".1\" /></Association></Schema><Schema Namespace=\"Default\" xmlns=\"http://schemas.m" +
                "icrosoft.com/ado/2009/11/edm\"><EntityContainer Name=\"Container\" m:IsDefaultEntit" +
                "yContainer=\"true\"><EntitySet Name=\"Titles\" EntityType=\"LibraryManagement.ObjectM" +
                "odel.Title\" /><EntitySet Name=\"Levels\" EntityType=\"LibraryManagement.ObjectModel" +
                ".Level\" /><EntitySet Name=\"TitleCategories\" EntityType=\"LibraryManagement.Object" +
                "Model.TitleCategory\" /><EntitySet Name=\"Books\" EntityType=\"LibraryManagement.Obj" +
                "ectModel.Book\" /><EntitySet Name=\"BookConditions\" EntityType=\"LibraryManagement." +
                "ObjectModel.BookCondition\" /><EntitySet Name=\"Fairies\" EntityType=\"LibraryManage" +
                "ment.ObjectModel.Fairy\" /><EntitySet Name=\"TitleLists\" EntityType=\"LibraryManage" +
                "ment.ObjectModel.TitleList\" /><EntitySet Name=\"CheckInRecords\" EntityType=\"Libra" +
                "ryManagement.ObjectModel.CheckInRecord\" /><AssociationSet Name=\"LibraryManagemen" +
                "t_ObjectModel_Title_TitleCategory_LibraryManagement_ObjectModel_TitleCategory_Ti" +
                "tleCategoryPartnerSet\" Association=\"LibraryManagement.ObjectModel.LibraryManagem" +
                "ent_ObjectModel_Title_TitleCategory_LibraryManagement_Objec";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart1 = "tModel_TitleCategory_TitleCategoryPartner\"><End Role=\"TitleCategoryPartner\" Entit" +
                "ySet=\"Titles\" /><End Role=\"TitleCategory\" EntitySet=\"TitleCategories\" /></Associ" +
                "ationSet><AssociationSet Name=\"LibraryManagement_ObjectModel_Title_Level_Library" +
                "Management_ObjectModel_Level_LevelPartnerSet\" Association=\"LibraryManagement.Obj" +
                "ectModel.LibraryManagement_ObjectModel_Title_Level_LibraryManagement_ObjectModel" +
                "_Level_LevelPartner\"><End Role=\"LevelPartner\" EntitySet=\"Titles\" /><End Role=\"Le" +
                "vel\" EntitySet=\"Levels\" /></AssociationSet><AssociationSet Name=\"LibraryManageme" +
                "nt_ObjectModel_Book_Title_LibraryManagement_ObjectModel_Title_TitlePartnerSet\" A" +
                "ssociation=\"LibraryManagement.ObjectModel.LibraryManagement_ObjectModel_Book_Tit" +
                "le_LibraryManagement_ObjectModel_Title_TitlePartner\"><End Role=\"TitlePartner\" En" +
                "titySet=\"Books\" /><End Role=\"Title\" EntitySet=\"Titles\" /></AssociationSet><Assoc" +
                "iationSet Name=\"LibraryManagement_ObjectModel_Book_BookCondition_LibraryManageme" +
                "nt_ObjectModel_BookCondition_BookConditionPartnerSet\" Association=\"LibraryManage" +
                "ment.ObjectModel.LibraryManagement_ObjectModel_Book_BookCondition_LibraryManagem" +
                "ent_ObjectModel_BookCondition_BookConditionPartner\"><End Role=\"BookConditionPart" +
                "ner\" EntitySet=\"Books\" /><End Role=\"BookCondition\" EntitySet=\"BookConditions\" />" +
                "</AssociationSet><AssociationSet Name=\"LibraryManagement_ObjectModel_CheckInReco" +
                "rd_Book_LibraryManagement_ObjectModel_Book_BookPartnerSet\" Association=\"LibraryM" +
                "anagement.ObjectModel.LibraryManagement_ObjectModel_CheckInRecord_Book_LibraryMa" +
                "nagement_ObjectModel_Book_BookPartner\"><End Role=\"BookPartner\" EntitySet=\"CheckI" +
                "nRecords\" /><End Role=\"Book\" EntitySet=\"Books\" /></AssociationSet><AssociationSe" +
                "t Name=\"LibraryManagement_ObjectModel_CheckInRecord_Fairy_LibraryManagement_Obje" +
                "ctModel_Fairy_FairyPartnerSet\" Association=\"LibraryManagement.ObjectModel.Librar" +
                "yManagement_ObjectModel_CheckInRecord_Fairy_LibraryManagement_ObjectModel_Fairy_" +
                "FairyPartner\"><End Role=\"FairyPartner\" EntitySet=\"CheckInRecords\" /><End Role=\"F" +
                "airy\" EntitySet=\"Fairies\" /></AssociationSet></EntityContainer></Schema></edmx:D" +
                "ataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0, ModelPart1);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.Title in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Titles")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Title : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Title object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="titleCategory_Id">Initial value of TitleCategory_Id.</param>
        /// <param name="level_Id">Initial value of Level_Id.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Title CreateTitle(int ID, string name, decimal price, int titleCategory_Id, int level_Id, bool isActive)
        {
            Title title = new Title();
            title.Id = ID;
            title.Name = name;
            title.Price = price;
            title.TitleCategory_Id = titleCategory_Id;
            title.Level_Id = level_Id;
            title.IsActive = isActive;
            return title;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Author
        {
            get
            {
                return this._Author;
            }
            set
            {
                this.OnAuthorChanging(value);
                this._Author = value;
                this.OnAuthorChanged();
                this.OnPropertyChanged("Author");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Author;
        partial void OnAuthorChanging(string value);
        partial void OnAuthorChanged();
        /// <summary>
        /// There are no comments for Property Publisher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this._Publisher = value;
                this.OnPublisherChanged();
                this.OnPropertyChanged("Publisher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property TitleCategory_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TitleCategory_Id
        {
            get
            {
                return this._TitleCategory_Id;
            }
            set
            {
                this.OnTitleCategory_IdChanging(value);
                this._TitleCategory_Id = value;
                this.OnTitleCategory_IdChanged();
                this.OnPropertyChanged("TitleCategory_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TitleCategory_Id;
        partial void OnTitleCategory_IdChanging(int value);
        partial void OnTitleCategory_IdChanged();
        /// <summary>
        /// There are no comments for Property Level_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Level_Id
        {
            get
            {
                return this._Level_Id;
            }
            set
            {
                this.OnLevel_IdChanging(value);
                this._Level_Id = value;
                this.OnLevel_IdChanged();
                this.OnPropertyChanged("Level_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Level_Id;
        partial void OnLevel_IdChanging(int value);
        partial void OnLevel_IdChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this._IsActive = value;
                this.OnIsActiveChanged();
                this.OnPropertyChanged("IsActive");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for TitleCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public TitleCategory TitleCategory
        {
            get
            {
                return this._TitleCategory;
            }
            set
            {
                this._TitleCategory = value;
                this.OnPropertyChanged("TitleCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private TitleCategory _TitleCategory;
        /// <summary>
        /// There are no comments for Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Level Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this._Level = value;
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Level _Level;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.Level in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Levels")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Level : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Level object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Level CreateLevel(int ID, string name)
        {
            Level level = new Level();
            level.Id = ID;
            level.Name = name;
            return level;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.TitleCategory in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TitleCategories")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class TitleCategory : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TitleCategory object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TitleCategory CreateTitleCategory(int ID, string name)
        {
            TitleCategory titleCategory = new TitleCategory();
            titleCategory.Id = ID;
            titleCategory.Name = name;
            return titleCategory;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.Book in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Books")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Book : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Book object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="title_Id">Initial value of Title_Id.</param>
        /// <param name="purchaseDate">Initial value of PurchaseDate.</param>
        /// <param name="bookCondition_Id">Initial value of BookCondition_Id.</param>
        /// <param name="issuedStatus">Initial value of IssuedStatus.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Book CreateBook(int ID, int title_Id, global::System.DateTime purchaseDate, int bookCondition_Id, bool issuedStatus)
        {
            Book book = new Book();
            book.Id = ID;
            book.Title_Id = title_Id;
            book.PurchaseDate = purchaseDate;
            book.BookCondition_Id = bookCondition_Id;
            book.IssuedStatus = issuedStatus;
            return book;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Barcode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Barcode
        {
            get
            {
                return this._Barcode;
            }
            set
            {
                this.OnBarcodeChanging(value);
                this._Barcode = value;
                this.OnBarcodeChanged();
                this.OnPropertyChanged("Barcode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Barcode;
        partial void OnBarcodeChanging(string value);
        partial void OnBarcodeChanged();
        /// <summary>
        /// There are no comments for Property Title_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Title_Id
        {
            get
            {
                return this._Title_Id;
            }
            set
            {
                this.OnTitle_IdChanging(value);
                this._Title_Id = value;
                this.OnTitle_IdChanged();
                this.OnPropertyChanged("Title_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Title_Id;
        partial void OnTitle_IdChanging(int value);
        partial void OnTitle_IdChanged();
        /// <summary>
        /// There are no comments for Property PurchaseDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime PurchaseDate
        {
            get
            {
                return this._PurchaseDate;
            }
            set
            {
                this.OnPurchaseDateChanging(value);
                this._PurchaseDate = value;
                this.OnPurchaseDateChanged();
                this.OnPropertyChanged("PurchaseDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _PurchaseDate;
        partial void OnPurchaseDateChanging(global::System.DateTime value);
        partial void OnPurchaseDateChanged();
        /// <summary>
        /// There are no comments for Property BookCondition_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int BookCondition_Id
        {
            get
            {
                return this._BookCondition_Id;
            }
            set
            {
                this.OnBookCondition_IdChanging(value);
                this._BookCondition_Id = value;
                this.OnBookCondition_IdChanged();
                this.OnPropertyChanged("BookCondition_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _BookCondition_Id;
        partial void OnBookCondition_IdChanging(int value);
        partial void OnBookCondition_IdChanged();
        /// <summary>
        /// There are no comments for Property DamLostDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> DamLostDate
        {
            get
            {
                return this._DamLostDate;
            }
            set
            {
                this.OnDamLostDateChanging(value);
                this._DamLostDate = value;
                this.OnDamLostDateChanged();
                this.OnPropertyChanged("DamLostDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _DamLostDate;
        partial void OnDamLostDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnDamLostDateChanged();
        /// <summary>
        /// There are no comments for Property IssuedStatus in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool IssuedStatus
        {
            get
            {
                return this._IssuedStatus;
            }
            set
            {
                this.OnIssuedStatusChanging(value);
                this._IssuedStatus = value;
                this.OnIssuedStatusChanged();
                this.OnPropertyChanged("IssuedStatus");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _IssuedStatus;
        partial void OnIssuedStatusChanging(bool value);
        partial void OnIssuedStatusChanged();
        /// <summary>
        /// There are no comments for Title in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Title Title
        {
            get
            {
                return this._Title;
            }
            set
            {
                this._Title = value;
                this.OnPropertyChanged("Title");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Title _Title;
        /// <summary>
        /// There are no comments for BookCondition in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public BookCondition BookCondition
        {
            get
            {
                return this._BookCondition;
            }
            set
            {
                this._BookCondition = value;
                this.OnPropertyChanged("BookCondition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private BookCondition _BookCondition;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.BookCondition in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BookConditions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class BookCondition : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new BookCondition object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BookCondition CreateBookCondition(int ID, string name)
        {
            BookCondition bookCondition = new BookCondition();
            bookCondition.Id = ID;
            bookCondition.Name = name;
            return bookCondition;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.Fairy in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Fairies")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Fairy : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Fairy object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Fairy CreateFairy(int ID, string name)
        {
            Fairy fairy = new Fairy();
            fairy.Id = ID;
            fairy.Name = name;
            return fairy;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.TitleList in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("TitleLists")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class TitleList : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new TitleList object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="price">Initial value of Price.</param>
        /// <param name="titleCategory_Id">Initial value of TitleCategory_Id.</param>
        /// <param name="level_Id">Initial value of Level_Id.</param>
        /// <param name="bookCount">Initial value of BookCount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static TitleList CreateTitleList(int ID, decimal price, int titleCategory_Id, int level_Id, int bookCount)
        {
            TitleList titleList = new TitleList();
            titleList.Id = ID;
            titleList.Price = price;
            titleList.TitleCategory_Id = titleCategory_Id;
            titleList.Level_Id = level_Id;
            titleList.BookCount = bookCount;
            return titleList;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Author in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Author
        {
            get
            {
                return this._Author;
            }
            set
            {
                this.OnAuthorChanging(value);
                this._Author = value;
                this.OnAuthorChanged();
                this.OnPropertyChanged("Author");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Author;
        partial void OnAuthorChanging(string value);
        partial void OnAuthorChanged();
        /// <summary>
        /// There are no comments for Property Publisher in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this._Publisher = value;
                this.OnPublisherChanged();
                this.OnPropertyChanged("Publisher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// There are no comments for Property Price in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal Price
        {
            get
            {
                return this._Price;
            }
            set
            {
                this.OnPriceChanging(value);
                this._Price = value;
                this.OnPriceChanged();
                this.OnPropertyChanged("Price");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _Price;
        partial void OnPriceChanging(decimal value);
        partial void OnPriceChanged();
        /// <summary>
        /// There are no comments for Property TitleCategory_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int TitleCategory_Id
        {
            get
            {
                return this._TitleCategory_Id;
            }
            set
            {
                this.OnTitleCategory_IdChanging(value);
                this._TitleCategory_Id = value;
                this.OnTitleCategory_IdChanged();
                this.OnPropertyChanged("TitleCategory_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _TitleCategory_Id;
        partial void OnTitleCategory_IdChanging(int value);
        partial void OnTitleCategory_IdChanged();
        /// <summary>
        /// There are no comments for Property TitleCategory in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string TitleCategory
        {
            get
            {
                return this._TitleCategory;
            }
            set
            {
                this.OnTitleCategoryChanging(value);
                this._TitleCategory = value;
                this.OnTitleCategoryChanged();
                this.OnPropertyChanged("TitleCategory");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _TitleCategory;
        partial void OnTitleCategoryChanging(string value);
        partial void OnTitleCategoryChanged();
        /// <summary>
        /// There are no comments for Property Level_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Level_Id
        {
            get
            {
                return this._Level_Id;
            }
            set
            {
                this.OnLevel_IdChanging(value);
                this._Level_Id = value;
                this.OnLevel_IdChanged();
                this.OnPropertyChanged("Level_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Level_Id;
        partial void OnLevel_IdChanging(int value);
        partial void OnLevel_IdChanged();
        /// <summary>
        /// There are no comments for Property Level in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Level
        {
            get
            {
                return this._Level;
            }
            set
            {
                this.OnLevelChanging(value);
                this._Level = value;
                this.OnLevelChanged();
                this.OnPropertyChanged("Level");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Level;
        partial void OnLevelChanging(string value);
        partial void OnLevelChanged();
        /// <summary>
        /// There are no comments for Property BookCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int BookCount
        {
            get
            {
                return this._BookCount;
            }
            set
            {
                this.OnBookCountChanging(value);
                this._BookCount = value;
                this.OnBookCountChanged();
                this.OnPropertyChanged("BookCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _BookCount;
        partial void OnBookCountChanging(int value);
        partial void OnBookCountChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for LibraryManagement.ObjectModel.CheckInRecord in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("CheckInRecords")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class CheckInRecord : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CheckInRecord object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="book_Id">Initial value of Book_Id.</param>
        /// <param name="fairy_Id">Initial value of Fairy_Id.</param>
        /// <param name="issueDate">Initial value of IssueDate.</param>
        /// <param name="checkInDate">Initial value of CheckInDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static CheckInRecord CreateCheckInRecord(int ID, int book_Id, int fairy_Id, global::System.DateTime issueDate, global::System.DateTime checkInDate)
        {
            CheckInRecord checkInRecord = new CheckInRecord();
            checkInRecord.Id = ID;
            checkInRecord.Book_Id = book_Id;
            checkInRecord.Fairy_Id = fairy_Id;
            checkInRecord.IssueDate = issueDate;
            checkInRecord.CheckInDate = checkInDate;
            return checkInRecord;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Book_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Book_Id
        {
            get
            {
                return this._Book_Id;
            }
            set
            {
                this.OnBook_IdChanging(value);
                this._Book_Id = value;
                this.OnBook_IdChanged();
                this.OnPropertyChanged("Book_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Book_Id;
        partial void OnBook_IdChanging(int value);
        partial void OnBook_IdChanged();
        /// <summary>
        /// There are no comments for Property Fairy_Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Fairy_Id
        {
            get
            {
                return this._Fairy_Id;
            }
            set
            {
                this.OnFairy_IdChanging(value);
                this._Fairy_Id = value;
                this.OnFairy_IdChanged();
                this.OnPropertyChanged("Fairy_Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Fairy_Id;
        partial void OnFairy_IdChanging(int value);
        partial void OnFairy_IdChanged();
        /// <summary>
        /// There are no comments for Property IssueDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime IssueDate
        {
            get
            {
                return this._IssueDate;
            }
            set
            {
                this.OnIssueDateChanging(value);
                this._IssueDate = value;
                this.OnIssueDateChanged();
                this.OnPropertyChanged("IssueDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _IssueDate;
        partial void OnIssueDateChanging(global::System.DateTime value);
        partial void OnIssueDateChanged();
        /// <summary>
        /// There are no comments for Property CheckInDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime CheckInDate
        {
            get
            {
                return this._CheckInDate;
            }
            set
            {
                this.OnCheckInDateChanging(value);
                this._CheckInDate = value;
                this.OnCheckInDateChanged();
                this.OnPropertyChanged("CheckInDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _CheckInDate;
        partial void OnCheckInDateChanging(global::System.DateTime value);
        partial void OnCheckInDateChanged();
        /// <summary>
        /// There are no comments for Book in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Book Book
        {
            get
            {
                return this._Book;
            }
            set
            {
                this._Book = value;
                this.OnPropertyChanged("Book");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Book _Book;
        /// <summary>
        /// There are no comments for Fairy in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public Fairy Fairy
        {
            get
            {
                return this._Fairy;
            }
            set
            {
                this._Fairy = value;
                this.OnPropertyChanged("Fairy");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private Fairy _Fairy;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
